#!/bin/sh
# vim: ts=4 sw=4 expandtab
if [ $# -eq 2 ]; then
    in="$1"
    out="$2"
elif [ $# -eq 1 ]; then
    in="$1"
    out="$1.bin"
else
    echo "Usage: hex2bin INPUT.HEX [OUTPUT.BIN]" >&2
    exit 1
fi
exec srec_cat "$in" -Intel -Output "$out" -Binary
